---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# speechcollectr

<!-- badges: start -->
<!-- badges: end -->

NOTE (August 2021): This package is currently under development. New functions in speechcollectr are being added daily! Stay tuned for more R tools for speech collection. 

The goal of speechcollectr is to provide tools for speech production and perception experiments. In the context of the COVID-19 pandemic, many speech researchers have had to either stop data collection or move to web-based data collection. This generally requires researchers to familiarize themselves with a new software. Speechcollectr, however, provides tools for web-based data collection in R, a language that many speech scientists are already familiar with. 

In its full version, speechcollectr will include R shiny buttons for audio playback, WAV file audio recording capabilities, simple games for participants to play as data is collected, and tools for acoustic analysis to present feedback to participants. 

## Installation
This project is not yet available on CRAN. For now, you can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("abbey-thomas/speechcollectr")
```
